export const jobData = [
  {
    id: "673367c463d0ba02a7c78473",
    title: "Software Engineer",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse euismod nunc vel nisi sagittis, vitae dictum tortor pharetra.",
    salary: 85000,
    posted_on: "2024-10-01",
    last_date_to_apply: "2024-10-15",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78474",
    title: "Data Scientist",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Etiam viverra ante nec diam scelerisque, eu rutrum ligula blandit.",
    salary: 95000,
    posted_on: "2024-10-02",
    last_date_to_apply: "2024-10-20",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78475",
    title: "Product Manager",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et orci nec orci gravida malesuada. Curabitur tristique ex vel ligula lacinia.",
    salary: 105000,
    posted_on: "2024-10-05",
    last_date_to_apply: "2024-10-25",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78476",
    title: "UI/UX Designer",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer malesuada urna eu mi auctor, ac pretium ante tincidunt. Pellentesque in lorem et justo tristique condimentum.",
    salary: 70000,
    posted_on: "2024-10-10",
    last_date_to_apply: "2024-10-30",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78477",
    title: "Full Stack Developer",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vel risus non enim tristique scelerisque sit amet ut magna. Cras sit amet libero eu nunc consequat laoreet.",
    salary: 92000,
    posted_on: "2024-10-15",
    last_date_to_apply: "2024-11-05",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78478",
    title: "Marketing Specialist",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus euismod vehicula ipsum at mollis. Nulla auctor felis ut turpis iaculis, in cursus magna sollicitudin.",
    salary: 65000,
    posted_on: "2024-10-18",
    last_date_to_apply: "2024-11-07",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78479",
    title: "HR Manager",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur consequat nunc at augue suscipit, sit amet auctor arcu dictum. Aenean nec purus sit amet sapien vehicula facilisis.",
    salary: 75000,
    posted_on: "2024-10-20",
    last_date_to_apply: "2024-11-10",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78480",
    title: "Business Analyst",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In efficitur nisi at turpis volutpat, sit amet dignissim urna maximus. Sed nec nulla ac lorem sollicitudin consequat.",
    salary: 80000,
    posted_on: "2024-10-22",
    last_date_to_apply: "2024-11-12",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78481",
    title: "DevOps Engineer",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vel lorem a nisl elementum facilisis. Morbi ut ante augue. Curabitur ac ante in metus luctus viverra.",
    salary: 96000,
    posted_on: "2024-10-25",
    last_date_to_apply: "2024-11-15",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78482",
    title: "QA Engineer",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit lectus at nunc dignissim, sed elementum urna faucibus. Sed at diam ut sem viverra laoreet.",
    salary: 70000,
    posted_on: "2024-10-28",
    last_date_to_apply: "2024-11-18",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78483",
    title: "Sales Executive",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae augue at velit luctus sodales. Aenean efficitur dolor id nunc mollis, a viverra purus venenatis.",
    salary: 55000,
    posted_on: "2024-10-30",
    last_date_to_apply: "2024-11-20",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78484",
    title: "Content Writer",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam erat volutpat. Nunc non orci a orci condimentum iaculis. Sed sollicitudin tristique neque sit amet vehicula.",
    salary: 40000,
    posted_on: "2024-11-01",
    last_date_to_apply: "2024-11-21",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78485",
    title: "Network Administrator",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus scelerisque mauris ut dui viverra, et cursus purus posuere. Fusce pharetra purus ut erat scelerisque auctor.",
    salary: 78000,
    posted_on: "2024-11-05",
    last_date_to_apply: "2024-11-25",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78486",
    title: "Technical Support Specialist",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sed ligula ac elit tincidunt volutpat. Cras fringilla leo vel orci accumsan, non ultricies risus dapibus.",
    salary: 60000,
    posted_on: "2024-11-07",
    last_date_to_apply: "2024-11-27",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78487",
    title: "Customer Support Representative",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor augue eu risus sollicitudin, et pharetra lectus luctus. Ut mollis ipsum nec est viverra facilisis.",
    salary: 45000,
    posted_on: "2024-11-10",
    last_date_to_apply: "2024-11-30",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78488",
    title: "Security Analyst",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae turpis et odio scelerisque vehicula sit amet non magna. Curabitur ut euismod purus.",
    salary: 100000,
    posted_on: "2024-11-12",
    last_date_to_apply: "2024-12-02",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78489",
    title: "System Administrator",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque gravida ligula et tortor tincidunt, et volutpat sapien luctus. Nulla facilisi.",
    salary: 85000,
    posted_on: "2024-11-15",
    last_date_to_apply: "2024-12-05",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78490",
    title: "Database Administrator",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet suscipit arcu. Etiam ut magna ac velit maximus fermentum at eget ligula.",
    salary: 95000,
    posted_on: "2024-11-18",
    last_date_to_apply: "2024-12-08",
    applicants: [],
  },
  {
    id: "673367c463d0ba02a7c78491",
    title: "Cloud Engineer",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget lorem a metus condimentum tristique. Nulla non diam vitae velit elementum varius.",
    salary: 110000,
    posted_on: "2024-11-20",
    last_date_to_apply: "2024-12-10",
    applicants: [],
  },
];

export const candidatesData = [
  {
    id: "673367c463d0ba02a7c78501",
    title: "Software Engineer",
    name: "John Doe",
    address: "1234 Elm St, Springfield, IL, 62701",
    email: "johndoe@example.com",
    skills: ["JavaScript", "Node.js", "React", "SQL"],
    experience: 3,
    resume_link: "http://example.com/resume/johndoe",
    status: "Applied",
  },
  {
    id: "673367c463d0ba02a7c78502",
    title: "Data Scientist",
    name: "Jane Smith",
    address: "5678 Maple Ave, Chicago, IL, 60601",
    email: "janesmith@example.com",
    skills: ["Python", "Machine Learning", "Pandas", "TensorFlow"],
    experience: 5,
    resume_link: "http://example.com/resume/janesmith",
    status: "Under Review",
  },
  {
    id: "673367c463d0ba02a7c78503",
    title: "Product Manager",
    name: "Alice Johnson",
    address: "9101 Oak Blvd, Naperville, IL, 60540",
    email: "alice.johnson@example.com",
    skills: [
      "Agile",
      "Product Strategy",
      "Leadership",
      "Stakeholder Management",
    ],
    experience: 7,
    resume_link: "http://example.com/resume/alicejohnson",
    status: "Shortlisted",
  },
  {
    id: "673367c463d0ba02a7c78504",
    title: "Full Stack Developer",
    name: "Robert Brown",
    address: "2468 Birch Rd, Peoria, IL, 61602",
    email: "robert.brown@example.com",
    skills: ["HTML", "CSS", "React", "Node.js", "MongoDB"],
    experience: 4,
    resume_link: "http://example.com/resume/robertbrown",
    status: "Applied",
  },
  {
    id: "673367c463d0ba02a7c78505",
    title: "HR Manager",
    name: "Linda Miller",
    address: "1357 Pine St, Bloomington, IL, 61701",
    email: "linda.miller@example.com",
    skills: [
      "Recruiting",
      "Employee Relations",
      "Conflict Resolution",
      "Payroll Management",
    ],
    experience: 6,
    resume_link: "http://example.com/resume/lindamiller",
    status: "Under Review",
  },
  {
    id: "673367c463d0ba02a7c78506",
    title: "UI/UX Designer",
    name: "Michael Davis",
    address: "8642 Cedar Dr, Joliet, IL, 60431",
    email: "michael.davis@example.com",
    skills: [
      "Sketch",
      "Figma",
      "Prototyping",
      "User Testing",
      "Interaction Design",
    ],
    experience: 3,
    resume_link: "http://example.com/resume/michaeldavis",
    status: "Shortlisted",
  },
  {
    id: "673367c463d0ba02a7c78507",
    title: "Sales Executive",
    name: "Sophia Martinez",
    address: "1720 Maple St, Elgin, IL, 60123",
    email: "sophia.martinez@example.com",
    skills: ["Salesforce", "Negotiation", "Cold Calling", "CRM"],
    experience: 2,
    resume_link: "http://example.com/resume/sophiamartinez",
    status: "Applied",
  },
  {
    id: "673367c463d0ba02a7c78508",
    title: "QA Engineer",
    name: "William Taylor",
    address: "2498 Spruce Rd, Champaign, IL, 61820",
    email: "william.taylor@example.com",
    skills: ["Selenium", "JUnit", "Automation Testing", "Manual Testing"],
    experience: 4,
    resume_link: "http://example.com/resume/williamtaylor",
    status: "Shortlisted",
  },
  {
    id: "673367c463d0ba02a7c78509",
    title: "Business Analyst",
    name: "Emily Anderson",
    address: "7851 Oakwood Ave, Rockford, IL, 61101",
    email: "emily.anderson@example.com",
    skills: ["Business Modeling", "Data Analysis", "Excel", "SQL"],
    experience: 5,
    resume_link: "http://example.com/resume/emilyanderson",
    status: "Under Review",
  },
  {
    id: "673367c463d0ba02a7c78510",
    title: "Security Analyst",
    name: "David Wilson",
    address: "3684 Ash Ln, Aurora, IL, 60506",
    email: "david.wilson@example.com",
    skills: [
      "Firewall Configuration",
      "Incident Response",
      "Penetration Testing",
      "Risk Management",
    ],
    experience: 6,
    resume_link: "http://example.com/resume/davidwilson",
    status: "Applied",
  },
  {
    id: "673367c463d0ba02a7c78511",
    title: "Software Architect",
    name: "James Harris",
    address: "5432 Willow Ave, Decatur, IL, 62521",
    email: "james.harris@example.com",
    skills: ["Java", "Spring", "Microservices", "System Design"],
    experience: 8,
    resume_link: "http://example.com/resume/jamesharris",
    status: "Shortlisted",
  },
  {
    id: "673367c463d0ba02a7c78512",
    title: "Marketing Manager",
    name: "Olivia Clark",
    address: "2341 Elm Rd, Bloomington, IL, 61704",
    email: "olivia.clark@example.com",
    skills: ["SEO", "Content Marketing", "Branding", "Social Media Strategy"],
    experience: 5,
    resume_link: "http://example.com/resume/oliviaclark",
    status: "Under Review",
  },
  {
    id: "673367c463d0ba02a7c78513",
    title: "DevOps Engineer",
    name: "Ethan Lewis",
    address: "1342 Pine Blvd, Joliet, IL, 60435",
    email: "ethan.lewis@example.com",
    skills: ["Docker", "Kubernetes", "CI/CD", "Terraform", "AWS"],
    experience: 4,
    resume_link: "http://example.com/resume/ethanlewis",
    status: "Applied",
  },
  {
    id: "673367c463d0ba02a7c78514",
    title: "Network Engineer",
    name: "Mason Moore",
    address: "7653 Cedar St, Naperville, IL, 60540",
    email: "mason.moore@example.com",
    skills: ["Networking", "Routing", "Switching", "Cisco", "Firewalls"],
    experience: 6,
    resume_link: "http://example.com/resume/masonmoore",
    status: "Applied",
  },
  {
    id: "673367c463d0ba02a7c78515",
    title: "Front-End Developer",
    name: "Sophia White",
    address: "9812 Oak Rd, Peoria, IL, 61615",
    email: "sophia.white@example.com",
    skills: ["HTML", "CSS", "JavaScript", "React", "Vue.js"],
    experience: 2,
    resume_link: "http://example.com/resume/sophiawhite",
    status: "Under Review",
  },
  {
    id: "673367c463d0ba02a7c78516",
    title: "Graphic Designer",
    name: "Henry Walker",
    address: "5432 Birch Dr, Rockford, IL, 61107",
    email: "henry.walker@example.com",
    skills: ["Photoshop", "Illustrator", "InDesign", "UI Design"],
    experience: 3,
    resume_link: "http://example.com/resume/henrywalker",
    status: "Shortlisted",
  },
  {
    id: "673367c463d0ba02a7c78517",
    title: "Business Development Manager",
    name: "Charlotte Robinson",
    address: "2307 Maple Dr, Aurora, IL, 60506",
    email: "charlotte.robinson@example.com",
    skills: [
      "Sales Strategy",
      "Market Research",
      "Negotiation",
      "Client Relations",
    ],
    experience: 7,
    resume_link: "http://example.com/resume/charlotterobinson",
    status: "Under Review",
  },
  {
    id: "673367c463d0ba02a7c78518",
    title: "Project Manager",
    name: "Amelia Taylor",
    address: "8156 Spruce Ln, Elgin, IL, 60120",
    email: "amelia.taylor@example.com",
    skills: [
      "Project Planning",
      "Budgeting",
      "Team Coordination",
      "Risk Management",
    ],
    experience: 6,
    resume_link: "http://example.com/resume/ameliataylor",
    status: "Shortlisted",
  },
  {
    id: "673367c463d0ba02a7c78519",
    title: "Cloud Engineer",
    name: "Lucas Harris",
    address: "4279 Oakwood Dr, Champaign, IL, 61820",
    email: "lucas.harris@example.com",
    skills: ["AWS", "Azure", "Cloud Architecture", "Infrastructure as Code"],
    experience: 4,
    resume_link: "http://example.com/resume/lucasharris",
    status: "Applied",
  },
  {
    id: "673367c463d0ba02a7c78520",
    title: "Cybersecurity Specialist",
    name: "Isabella Young",
    address: "3651 Maple St, Springfield, IL, 62704",
    email: "isabella.young@example.com",
    skills: [
      "Firewalls",
      "Intrusion Detection",
      "Encryption",
      "Penetration Testing",
    ],
    experience: 5,
    resume_link: "http://example.com/resume/isabellayoung",
    status: "Under Review",
  },
];
